### PR TITLE
[TSK-139] renamed DB, paths in .gitignore and moved docker-compose to qpay

### PR DESCRIPTION
**Pull request by adsukharev**

### CODE REVIEW

**Comment by adsukharev** [comment]
@kostya4201337 why are you renamed paths in .gitignore?

**Comment by konstantinwas** [comment]
> @kostya4201337 why are you renamed paths in .gitignore?

i guess intelij refactored it when i renamed test class

**Comment by adsukharev** [comment]
> > @kostya4201337 why are you renamed paths in .gitignore?
> 
> i guess intelij refactored it when i renamed test class

@kostya4201337 
I wrote to you 3 times in your PR to fix it.
If you don't understand, ask questions

**Comment by adsukharev** [comment]
You have to create a ticket in Notion to have a task id and description what you are going to do. Then create a bugfix branch. Then commit with correct task id.
Actually, we created yesterday a ticket with bugfix label. Why didn't you use it?
Ask questions before doing useless work. You need to cancel PR and do it again corrrectly

**Comment by adsukharev** [comment]
You created a docker-compose file in a root. That's correct. But you did not remove it from the `user-manager` folder.
You did the task incorrectly, because you did not create a correct task with clear description and did not show it to me for approval. 
If you don't understand, ask questions

**Comment by adsukharev** [comment]
If you don't understand, ask questions

**Comment by adsukharev** [comment]
If you don't understand, ask questions

**Comment by adsukharev** [comment]
If you don't understand, ask questions

**Comment by adsukharev** [comment]
If you don't understand, ask questions

**Comment by adsukharev** [comment]
If you don't understand, ask questions

**Pull request closed without merging**
