### PR TITLE
[TSK-234] remove password from user manager

### PR DESCRIPTION
**Pull request by Hoocki**

### CODE REVIEW

**Comment by adsukharev** [comment]
Why do you have 5 commits ? It does not make sense to review everything again. 
You have to create branch from master . It's a separate task.

**Comment by Hoocki** [comment]
> Why do you have 5 commits ? It does not make sense to review everything again. You have to create branch from master . It's a separate task.

I thought these commits are anyway will be in this branch, i will add them and do task

**Comment by adsukharev** [comment]
> > Why do you have 5 commits ? It does not make sense to review everything again. You have to create branch from master . It's a separate task.
> 
> 
> 
> I thought these commits are anyway will be in this branch, i will add them and do task

In that case, all people have to look into all these changes in 51 files and search for your real changes.

**Comment by Hoocki** [comment]
> > > Why do you have 5 commits ? It does not make sense to review everything again. You have to create branch from master . It's a separate task.
> > 
> > 
> > I thought these commits are anyway will be in this branch, i will add them and do task
> 
> In that case, all people have to look into all these changes in 51 files and search for your real changes.

ok, i will close this pr and recreate it without commits from service-discovery

**Comment by adsukharev** [comment]
> > > Why do you have 5 commits ? It does not make sense to review everything again. You have to create branch from master . It's a separate task.
> > 
> > 
> > 
> > I thought these commits are anyway will be in this branch, i will add them and do task
> 
> In that case, all people have to look into all these changes in 51 files and search for your real changes.

You have 2 options:
1) create new branch from master. Then cherry pick needed commit , PR to master
2) change target branch from master to service discovery in this PR

**Pull request closed without merging**
